apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        password: {{` "{{ .password }}" `}}
        admin-user: admin
  data:
    - secretKey: password
      remoteRef:
        key: grafana.admin
        property: password