app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/nextcloud
            tag: 28-fpm-alpine
  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host cloud.le-g.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: nextcloud-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /data
