renovate:
  cronjob:
    schedule: '0 9 * * *'  # Everyday at 09:00
  renovate:
    config: |
      {
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "repositories": ['le-g/homelab'];
        "autodiscover": false,
      }
  existingSecret: renovate-secret
