apiVersion: v2
name: immich
version: 0.0.0
dependencies:
  - name: immich
    version: 0.9.3
    repository: oci://ghcr.io/immich-app/immich-charts
  - name: postgresql
    version: 16.7.21
    repository: oci://registry-1.docker.io/bitnamicharts
