app-template:
  defaultPodOptions:
    hostname: headless-code
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/le-g/headless-code
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP
  persistence:
    data:
      accessMode: ReadWriteMany
      size: 10Gi
      globalMounts:
        - path: /home/user
          readOnly: false

