apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ index .Values "app-template" "controllers" "db" "containers" "postgres" "env" 3 "valueFrom" "secretKeyRef" "name"}}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: nextcloud.pgadminpassword
        property: password
