apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgresql-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        postgres-password: {{` "{{ .postgres_password }}" `}}
  data:
    - secretKey: postgres_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: immich.postgresql
        property: postgres_password