apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nas-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.181
    path: /mnt/main/immich
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nas-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: immich-nas-pv
  storageClassName: "" 