app-template:
  defaultPodOptions:
    hostNetwork: true
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/homeassistant/home-assistant
            tag: 2024.3
  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8123
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host homeassistant.le-g.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homeassistant-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: home-assistant-config
      globalMounts:
        - path: /config/configuration.yaml
          subPath: configuration.yaml
  configMaps:
    config:
      enabled: true
      data:
        configuration.yaml: |
          # Loads default set of integrations. Do not remove.
          default_config:

          # Load frontend themes from the themes folder
          frontend:
            themes: !include_dir_merge_named themes

          automation: !include automations.yaml
          script: !include scripts.yaml
          scene: !include scenes.yaml
          http:
            use_x_forwarded_for: true
            trusted_proxies:
              - 192.168.1.110
              - 192.168.1.111

