app-template:
  defaultPodOptions:
    hostNetwork: true
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/homeassistant/home-assistant
            tag: 2024.3
  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8123
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host homeassistant.le-g.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homeassistant-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /config
          readOnly: false
