app-template:
  defaultPodOptions:
    hostNetwork: true
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/homeassistant/home-assistant
            tag: 2024.3
        mosquitto:
          image:
            repository: docker.io/eclipse-mosquitto
            tag: 2.0
      initContainers:
        init-config:
          image:
            repository: docker.io/busybox
            tag: latest
          command: ['sh', '-c', 'cp /init-config/* /config']
  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8123
        mosquitto-mqtt:
          port: 1883
        moquitto-ws:
          port: 9001
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host homeassistant.le-g.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homeassistant-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /config
          readOnly: false
    config:
      enabled: true
      type: configMap
      name: home-assistant-config
      globalMounts:
        - path: /init-config/configuration.yaml
          subPath: configuration.yaml
        - path: /init-config/automations.yaml
          subPath: automations.yaml
        - path: /init-config/scripts.yaml
          subPath: scripts.yaml
        - path: /init-config/scenes.yaml
          subPath: scenes.yaml
        - path: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
  configMaps:
    config:
      enabled: true
      data:
        configuration.yaml: |
          # Loads default set of integrations. Do not remove.
          default_config:

          # Load frontend themes from the themes folder
          frontend:
            themes: !include_dir_merge_named themes

          automation: !include automations.yaml
          script: !include scripts.yaml
          scene: !include scenes.yaml
          http:
            use_x_forwarded_for: true
            trusted_proxies:
              - 192.168.1.110
              - 192.168.1.111
              - 10.0.0.0/16
        automations.yaml: |
          []
        scripts.yaml: |
          # Empty
        scenes.yaml: |
          # Empty
        mosquitto.conf: |
          listener 1883 0.0.0.0
          allow_anonymous true

