# Gitea
- name: gitea.admin
  data:
    - key: password
      length: 32
      special: true

# Paperless
- name: paperless.admin
  data:
    - key: PAPERLESS_ADMIN_PASSWORD
      length: 32
      special: true

# ntfy
- name: ntfy-relay.auth
  data:
    - key: password
      length: 32
      special: true

# nextcloud postgres
- name: nextcloud.pgadminpassword
  data:
    - key: password
      length: 32
      special: true

# grafana
- name: grafana.admin
  data:
    - key: password
      length: 32
      special: true