# ntfy
- name: ntfy-relay.auth
  data:
    - key: password
      length: 32
      special: true

# nextcloud postgres
- name: nextcloud.pgadminpassword
  data:
    - key: password
      length: 32
      special: true

# grafana
- name: grafana.admin
  data:
    - key: password
      length: 32
      special: true

# vaultwarden
- name: vaultwarden.admin
  data:
    - key: password
      length: 40
      special: true