apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ index .Values "n8n" "main" "secret" "n8n" "encryption_key" "valueFrom" "secretKeyRef" "name" }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        encryption_key: {{` "{{ .encryption_key }}" `}}
  data:
    - secretKey: encryption_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: n8n.encryptionkey
        property: encryption_key