ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
    1883: home-assistant/home-assistant:1883
